
server:
  port: 10012
spring:
  application:
    name: personal-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/banwoqiche?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 666888
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
mybatis:
  mapper-locations: classpath:mapping/*.xml